version: '2'

# Running BOTS with Dirmonitor and JobQueue Server enabled.
# The Supervisor uses environment variables SUPERVUSER for HTTP user login and
# SUPERVPASS for password.


services:
  bots-complete:
    build:
      context: .
      dockerfile: ./compose/bots_complete/Dockerfile
    ports:
      - "0.0.0.0:8080:8080"
      - "0.0.0.0:9001:9001"
    environment:
      - SUPERVUSER=bots
      - SUPERVPASS=botsbots
    command: /usr/local/bin/supervisord -c /etc/supervisor/supervisord.conf
    volumes:
      - ./config:/usr/local/lib/python2.7/dist-packages/bots/config
      - ./botssys:/usr/local/lib/python2.7/dist-packages/bots/botssys
      - ./usersys:/usr/local/lib/python2.7/dist-packages/bots/usersys
